# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems = {
    # Root SSD
    "/" = {
      label = "nixos";
      fsType = "btrfs";
      options = ["subvol=@" "compress=zstd"];
    };

    "/home" = {
      label = "nixos";
      fsType = "btrfs";
      options = ["subvol=@home" "compress=zstd"];
    };

    "/nix" = {
      label = "nixos";
      fsType = "btrfs";
      options = ["subvol=@nix" "compress=zstd" "noatime"];
    };

    "/var/log" = {
      label = "nixos";
      fsType = "btrfs";
      options = ["subvol=@log" "compress=zstd"];
    };

    # Boot EFI
    "/boot" = {
      device = "/dev/disk/by-label/boot";
      fsType = "vfat";
      options = ["fmask=0077" "dmask=0077"];
    };

    # Interal HDD
    "/hdd" = {
      label = "btrhd";
      fsType = "btrfs";
      options = ["subvol=@hdd2t" "autodefrag" "compress=zstd"];
    };

    "/hdd/backup" = {
      label = "btrhd";
      fsType = "btrfs";
      options = ["subvol=@backup" "autodefrag" "noatime" "compress=zstd:15"];
    };

    "/hdd/media" = {
      label = "btrhd";
      fsType = "btrfs";
      options = ["subvol=@media" "autodefrag" "noatime" "compress=zstd"];
    };

    "hdd/.temp" = {
      label = "btrhd";
      fsType = "btrfs";
      options = ["subvol=@temp" "autodefrag" "noatime" "compress=zstd"];
    };
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
